### ISSUE TITLE
[BUG] insecure and burp-replay forbidden

### ISSUE THREAD

**Issue by Darks1de42** [epi052/feroxbuster#1202] opened 2024-11-11 13:01 UTC
**Describe the bug**
```
error: the argument '--insecure' cannot be used with '--burp-replay'
```

**To Reproduce**
1. Use the options `--insecure` and `--burp-replay` together

**Expected behavior**
I would expect both options to work together since I can't see a reason, why this is forbidden.

**Environment (please complete the following information):**
 - feroxbuster version: 2.11.0
 - OS Arch

**Comment by epi052** [comment] 2024-11-11 13:26
howdy! 

the help for `--burp-replay`:

```Set --replay-proxy to http://127.0.0.1:8080 and set --insecure to true```

You're using a composite setting (`--burp-replay`) with a setting that the composite uses (`--insecure`). If you simply use `--burp-replay`, you'll see the following two settings in the banner.

```
 🎥  Replay Proxy          │ http://127.0.0.1:8080
 ...
 🔓  Insecure              │ true

```

closing this, since it's not a bug. If you disagree, feel free to reopen/continue the discussion. Thanks!

**Closed by epi052** 2024-11-11 13:26 UTC
Labels: bug

**Comment by Darks1de42** [comment] 2024-11-11 13:43
Thanks it works with `--replay-proxy`.     
I wanted to use it in autorecon and there is the insecure flag hardcoded.

**Comment by epi052** [comment] 2024-11-11 13:45
ahhhh, i see! Yea, `--replay-proxy` is the way then. Glad you got it sorted!
