### ISSUE TITLE
FeroxBuster giving no result for the existing directory

### ISSUE THREAD

**Issue by m-raheem** [epi052/feroxbuster#1100] opened 2024-03-05 18:52 UTC
![image](https://github.com/epi052/feroxbuster/assets/82972589/673fdc19-7c5d-41a3-b30c-462075eff73e)
Command i used 
`feroxbuster -u http://10.10.8.36/static/ -w num.txt -T 30`
Content of num.txt one per line
`00
01
02
03
04
05
06
07
08
09
10
11
12
13
14
15
16
`
existing directory is /00.

but feroxbuster is not listing it yet gobuster is listing it

**Comment by epi052** [comment] 2024-03-06 11:21
when ferox finds a target with directory listing enabled and extract-links is true, it ignored the wordlist and just parses the directory listing response. Could you show the page source of `/static/`? It looks like something on that page is preventing a parse, whether it's empty or the links are an unexpected type etc

if this is a public target, please let me know as well. 

Thanks for taking the time to submit!

**Comment by m-raheem** [comment] 2024-03-06 11:42
Directory listing is enabled and the directories are not listed.
Additionally it is a THM room.

**Comment by epi052** [comment] 2024-03-06 12:12
is it the valley room/box?

**Comment by m-raheem** [comment] 2024-03-06 13:30
> is it the valley room/box?

Yes It is that one. I would suggest to add a feature that first do check directory listing is enabled and then check the count of Url gain if it is equal to zero then  it must do the remaining directory busting from the wordlist.

**Comment by epi052** [comment] 2024-03-07 03:22
sounds like a duplicate of this one https://github.com/epi052/feroxbuster/issues/907

**Comment by m-raheem** [comment] 2024-03-07 18:36
> sounds like a duplicate of this one https://github.com/epi052/feroxbuster/issues/907

Got it thanks 💯

**Comment by epi052** [comment] 2024-03-30 20:12
closing as duplicate, feel free to reopen if needed

**Closed by epi052** 2024-03-30 20:12 UTC
Labels: bug
