### ISSUE TITLE
[BUG] Output flooding on some specific case

### ISSUE THREAD

**Issue by c0rv4x** [epi052/feroxbuster#361] opened 2021-10-01 12:59 UTC
**Describe the bug**

Hey!

Running scan against scanfactory.io results in the terminal being flooded with enormous amount of data.

![2021-10-01_15-58](https://user-images.githubusercontent.com/7037785/135623566-bf1b1813-3b98-4caf-94c8-32cb6f8e3dc4.png)
![2021-10-01_15-54](https://user-images.githubusercontent.com/7037785/135622950-064960e4-9bb6-4c0a-9939-ff0d2683cba6.png)

I am not sure of what is happenning here. Looks like it starts recursive bruteforcing and with that outputs every single request it has.

This problem is seen not only on scanfactory website but this is the first website that has the described problem and conscent to scan them.

**To Reproduce**

1. Run `feroxbuster -w ~/wordlists/no-extensions.txt -k --url  https://scanfactory.io`

**Expected behavior**

Expected to not have huge output of every request being sent

**Environment (please complete the following information):**

Arch linux
Feroxbuster: v2.3.3
Alacritty (but same in urxvt)

**Comment by epi052** [comment] 2021-10-01 13:19
Can you check if this is the problem/solution? 

https://epi052.github.io/feroxbuster-docs/docs/faq/progress-bars/

**Comment by c0rv4x** [comment] 2021-10-01 14:03
@epi052  thanks for a quick answer!

Not really. Maximum width doesn't help. Also putting `-q` doesn't fix the problem
![2021-10-01_17-03](https://user-images.githubusercontent.com/7037785/135633234-6a11f965-4456-4fae-ab99-9725e5634478.png)

**Comment by epi052** [comment] 2021-10-01 14:06
@c0rv4x not a problem.  It looks like you may own the domain, if so, am i free to scan and see if i can reproduce what you're seeing?

**Comment by c0rv4x** [comment] 2021-10-01 14:10
@epi052 yes. My email is anatoly at scanfactory dot io in case you want a verification from me

**Comment by epi052** [comment] 2021-10-01 14:15
good deal, i can take a look this evening and let you know. 

It feels like a terminal emulator / rendering problem, but I'll check it out.

**Comment by c0rv4x** [comment] 2021-10-01 14:38
Thought so too. But the same issue in urxvt and alacritty. Thanks anyway, will wait for your tests

**Comment by epi052** [comment] 2021-10-01 20:57
Scanning from my machine looks normal 

![image](https://user-images.githubusercontent.com/43392618/135685232-b429d6e0-4bc1-4538-bb64-69f6d3b0da4e.png)

**Comment by epi052** [comment] 2021-10-01 21:05
installed alacritty and ran it from that terminal as well, still looks good

**Comment by epi052** [comment] 2021-10-01 21:09
installed rxvt-unicode and ran a third scan, still looks good.  

Do you have a different VM / OS to try from?

**Comment by c0rv4x** [comment] 2021-10-01 23:29
Super weird! I will give it a try and let you know. Thanks for chechkin it out

I am thinking this might be zsh for some reason

**Comment by c0rv4x** [comment] 2021-10-02 00:22
I have just tested on MacBook and it works fine. I am trying to make it work on my arch linux as it is my main device.

I have tried using bash and no Xorg environment and the issue is still there. Wow. Do you have any advice on what to move further with the dissecting this issue?

**Comment by epi052** [comment] 2021-10-02 11:35
the terminal emulator, the font, and the width of your terminal vs. the width of your output are the three primary suspects in my mind. 

Do you use a PS1? Is it colored? If so, try exporting an ascii PS1

```
export PS1='> '
```

This shouldn't affect output that isn't on the same line as your prompt, but we can test it for funsies (i've seen terminal emulators behave poorly with colored PS1's when the line becomes too long, even if after rendering the ansi escape codes, it doesn't look long at all). 

You could post up the output of `env`. 

Have you tried something like xterm (i.e. a more traditional terminal emulator)? 

Can you try changing the font in one of your emulators to NotoColorEmoji?

**Comment by c0rv4x** [comment] 2021-10-02 12:22
OMG I just figured out.

In my wordlist I had the following entries:

```
.htaccess/
.htpasswd/
```

When a website had 403 on ht.* looks like it just went recursive scan on those dirs. I just deleted those and now it is fine. Pretty weird tho.

Sorry for the hassle and thanks for your help

**Comment by epi052** [comment] 2021-10-02 12:32
no worries, glad you got it resolved.  closing this issue

**Closed by epi052** 2021-10-02 12:32 UTC
Labels: bug, unconfirmed
