### ISSUE TITLE
[BUG] Feroxbuster fails to connect to live target

### ISSUE THREAD

**Issue by rew1nter** [epi052/feroxbuster#1181] opened 2024-07-01 07:20 UTC
**Describe the bug**
The URL is accessible but feroxbuster cant connect 
![image](https://github.com/epi052/feroxbuster/assets/64508791/1449615f-d186-41d1-bbbc-aa79927cd968)

**To Reproduce**

**Expected behavior**
To Fuzz as usual

**Traceback / Error Output**
If applicable, add error output to help explain your problem.

**Environment (please complete the following information):**
 - feroxbuster version: feroxbuster 2.10.4
 - OS: Arch

**Additional context**
I have the insecure flag set via an alias. Even without it, it wont work

**Comment by epi052** [comment] 2024-07-01 10:15
`rei.com` has some weird issues. Try adding `-H 'User-Agent: Firefox/120'`, it should work with that header.

**Comment by rew1nter** [comment] 2024-07-02 07:06
Interesting. It responds to httpie without any `User-Agent` header.

**Comment by epi052** [comment] 2024-08-25 10:52
My guess would be that httpie doesn't set a default header, or at least sets one that makes it through w/e filter rei uses. Closing this one since the issue is server-side. Please feel free to reopen if needed

**Closed by epi052** 2024-08-25 10:52 UTC
Labels: bug
