### ISSUE TITLE
Small screen width leads to repeating lines in output

### ISSUE THREAD

**Issue by watskenet** [epi052/feroxbuster#1038] opened 2023-11-29 04:30 UTC
if my screen size small , show to me wrong data in screen

**Comment by Pharisee** [comment] 2023-12-08 21:16
Instead of opening a new issue, I'll just expand on this one since (if it's not just a troll) there's a chance it's related.

Essentially when the window is small enough that the length of one of the lines exceeds it, the output bugs out and starts repeating lines and scrolling down the screen endlessly in a real ugly way. My guess is it seems like a problem with however the output lines are being updated/refreshed that doesn't like when the lines go past the far edge of the terminal window and are forced to wrap.

Dunno rust shit, so no clue where the issue is or if it's fixable, but figured I'd drop it in here since it was bugging me trying to figure out why the output looked like trash when everybody was saying it looked dope until I figured out I just needed to widen the window. Anyways, it's quality shit dude. Appreciate ya.

![image](https://github.com/epi052/feroxbuster/assets/18061324/62c9a505-4b9a-49b7-b1c8-49651d2c7a35)

**Comment by epi052** [comment] 2023-12-09 16:11
tysm! glad you're enjoying it

as for the output, this has been a known issue for a very long time. I use a library for handling terminal output and don't plan on trying to apply a fix for this particular issue. The workarounds are documented at the link below:

https://epi052.github.io/feroxbuster-docs/docs/faq/progress-bars/

i think the only reasonable fix is to check terminal width at startup and emit a warning to the user :thinking:

**Comment by epi052** [comment] 2024-02-24 10:34
morning! i was going to add a warning on small terminal width, but i can't actually reproduce this anymore. could you give it a shot and see if you can still get it to do this @Pharisee

**Comment by Pharisee** [comment] 2024-02-24 11:31
Ah. Sorry, I didn't respond before. Been a busy year so far. Just tested it again and it seems like the bug is only triggering in t-pain mode (aka `--auto-tune`) when the stoplight message displays (set rate limit, increased scan speed, etc.)

**Comment by epi052** [comment] 2024-02-25 20:29
thanks for that? What terminal are you using? i've tried 3 separate terminal emulators and still can't repro, even with auto-tune. 

all i really need to know is the terminal width at which i should warn users that things may get wonky. i could just say 80 or less and call it a day, but would like to be more specific. any chance you could get that info @Pharisee ?

**Comment by epi052** [comment] 2024-02-26 12:33
no worries, it sounds like there's not an easy static value with which we can warn folks. in that case, going to skip the warning and let current documentation/issues stand as-is. 

Thank you for your help with this!

**Closed** 2024-02-26 12:33 UTC
Labels: bug, wontfix
