### ISSUE TITLE
[BUG] - saved state scan - resume: unable to add new config options to the already saved state

### ISSUE THREAD

**Issue by xaeroborg** [epi052/feroxbuster#742] opened 2022-12-21 16:20 UTC
**Description**
My Need: Lets say a scan is running with a rate limit of 10 and I forgot to add a config like writing the result to a file and I want to  decrease the rate limit to 5. 
My Expectation: In general I'd hit ctrl+c and the scan will terminate saving the state of the current scan. I then use the following command `feroxbuster --resume-from ferox-http_localhost-1606947491.state --rate-limit 5 -o result.txt` 
What I get: feroxbuster is able to resume the scan and write the file to the specified result.txt but its unable to reduce or have any effect on the rate limit

**To Reproduce**
1. Run a directory scan with a rate limit of 10
2. Hit ctrl+c, feroxbuster will terminate and save the state of the current scan
3. Now resume the scan with the following command `feroxbuster --resume-from ferox-http_localhost-1606947491.state --rate-limit 5`
4. The scan will start but the rate doesnt change
**Expected behavior**
feroxbuster is able to resume the scan but its unable to reduce or have any effect on the rate limit

**Environment (please complete the following information):**
 - feroxbuster version: tested in both 2.6.4 and 2.7.2
 - OS: ubuntu 20.04

**Comment by epi052** [comment] 2022-12-21 17:10
thanks for submitting this! What you've described is the intended behavior, so we might have a bug in how the configurations are merged on resume. I'll take a look here soon. Thanks again!

**Comment by epi052** [comment] 2022-12-29 13:13
howdy @xaeroborg! I looked into this, and things appear to work for me. Am I missing something?

> note: a much more obvious change can be seen when the difference in rates is larger, i.e. 5 -> 100 or similar

run with `--rate-limit 10`
```
cargo run -- -u http://localhost:8000 -w tests/extra-words --rate-limit 10
```
```
 ___  ___  __   __     __      __         __   ___
|__  |__  |__) |__) | /  `    /  \ \_/ | |  \ |__  
|    |___ |  \ |  \ | \__,    \__/ / \ | |__/ |___
by Ben "epi" Risher 🤓                 ver: 2.7.2                                                                       
───────────────────────────┬──────────────────────                                                                      
 🎯  Target Url            │ http://localhost:8000                                                                      
 🚀  Threads               │ 50                                                                                         
 📖  Wordlist              │ tests/extra-words                                                                          
 👌  Status Codes          │ [200, 204, 301, 302, 307, 308, 401, 403, 405, 500]   
 💥  Timeout (secs)        │ 7                                                                                          
 🦡  User-Agent            │ feroxbuster/2.7.2
 💉  Config File           │ /home/epi/PycharmProjects/feroxbuster/ferox-config.toml                                   
 🤯  Header                │ Accept: text/html, application/json
 🏁  HTTP methods          │ [GET]
 🔃  Recursion Depth       │ 4
 🚧  Requests per Second   │ 10
───────────────────────────┴──────────────────────
 🏁  Press [ENTER] to use the Scan Management Menu™
──────────────────────────────────────────────────
204      GET        0l        0w        0c http://localhost:8000/Aaron
401      GET        8l       11w     2207c http://localhost:8000/A's
301      GET        7l       10w      797c http://localhost:8000/AOL's
🚨 Caught ctrl+c 🚨 saving scan state to ferox-http_localhost:8000-1672319188.state ...
[>-------------------] - 3s        10/102775  1h      found:2       errors:0      
[>-------------------] - 3s         8/102775  9/s     http://localhost:8000/ 
```

resume with `--rate-limit 5`
```
cargo run -- --resume-from ferox-http_localhost:8000-1672319188.state --rate-limit 5
```
```
 ___  ___  __   __     __      __         __   ___
|__  |__  |__) |__) | /  `    /  \ \_/ | |  \ |__
|    |___ |  \ |  \ | \__,    \__/ / \ | |__/ |___
by Ben "epi" Risher 🤓                 ver: 2.7.2
───────────────────────────┬──────────────────────
 🎯  Target Url            │ http://localhost:8000/
 🚀  Threads               │ 50
 📖  Wordlist              │ tests/extra-words
 👌  Status Codes          │ [200, 204, 301, 302, 307, 308, 401, 403, 405, 500]
 💥  Timeout (secs)        │ 7
 🦡  User-Agent            │ feroxbuster/2.7.2
 💉  Config File           │ /home/epi/PycharmProjects/feroxbuster/ferox-config.toml
 🤯  Header                │ Accept: text/html, application/json
 🏁  HTTP methods          │ [GET]
 🔃  Recursion Depth       │ 4
 🚧  Requests per Second   │ 5
───────────────────────────┴──────────────────────
 🏁  Press [ENTER] to use the Scan Management Menu™
──────────────────────────────────────────────────
204      GET        0l        0w        0c http://localhost:8000/Aaron
401      GET        8l       11w     2207c http://localhost:8000/A's
301      GET        7l       10w      797c http://localhost:8000/AOL's
500      GET        0l        0w        0c http://localhost:8000/AMD
🚨 Caught ctrl+c 🚨 saving scan state to ferox-http_localhost:8000-1672319205.state ...
[>-------------------] - 1s         6/102775  1h      found:4       errors:0      
[>-------------------] - 1s         4/102775  11/s    http://localhost:8000/ 
```

**Comment by xaeroborg** [comment] 2022-12-29 16:52
The issue that I had was whenever I changed the rate-limit increase/decrease the changes didnt take effect. For example in the above screenshot, at the very last line of the progress bar `[>-------------------] - 1s         4/102775  11/s    http://localhost:8000/` in my case: the timing part showed only "1/s" and the other issue I had was I had terminated the scan after 1 week and when I resumed it, the progress bar didnt show the exact duration from where it is continuing rather it showed more like its continuing from the beginning.

**Comment by epi052** [comment] 2022-12-30 01:54
> the timing part showed only "1/s"

the rate limiting can take a while to adjust as far as the output goes. how long did you wait to see if it went beyond the 1/s?

>  I had terminated the scan after 1 week and when I resumed it, the progress bar didnt show the exact duration from where it is continuing rather it showed more like its continuing from the beginning

if what you're referring to was a single directory (i.e. `[>-------------------] - 1s         4/102775  11/s    http://localhost:8000/`), then it makes sense that it starts over (see below).

when a scan is `ctrl+c`'d/resumed
- any directory that is cancelled/complete won't be rescanned
- any directory that isn't complete will start over from the beginning

The reasons that incomplete directories start over
- when i wrote that logic, the wordlist was unordered (it was a set data structure underneath)
- on top of being unordered, the requests are asynchronous
- finally, i don't store responses that aren't interesting. the only responses that are kept are ones that aren't filtered out

Putting all those together, (without rewriting things) I had no way of knowing what requests had been sent when a user pressed ctrl+c, and so couldn't resume from any point other than the beginning with any degree of certainty.

 Ok, so, that's the history lesson :grin: 

Things are a bit different now. The wordlist is a Vec (meaning it's in order). I think with a little bit of work, we could make a pretty reasonable guess at where to restart an in-progress directory. It's a bit more work than I have time for at the moment, but would happily guide/coach someone through a PR.

Going to change this to an enhancement to capture that work.

**Closed** 2022-12-30 01:56 UTC
Labels: bug, unconfirmed
